services:
  db:
    image: imresamu/postgis:17-3.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: maria_mineira
      POSTGRES_PASSWORD: maria_mineira
      POSTGRES_DB: maria_mineira_development
    ports:
      - "5432:5432"
    volumes:
      - maria_mineira_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maria_mineira"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  maria_mineira_postgres_data:
